# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  tags:
    - lists
    - cpp
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  script:
    - g++ -c linked_list.cpp
    - g++ -c aplJSON.cpp
  #artifacts:
  #  paths:
  #    - linked_list.o
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  #    cache:
  #      paths:
  #        - "*.o"

# run tests using the binary built before
test:
  tags:
    - lists
    - cpp
  stage: test
  before_script:
    - mkdir catch2
    - curl --insecure -L https://github.com/catchorg/Catch2/releases/download/v2.11.1/catch.hpp -o catch2/catch.hpp
  script:
    - ./CItests.sh
